### PR TITLE
don't return file array if start record is missing

### PR DESCRIPTION
**Pull request by pderouen**
When the srecord file doesn't contain a start address record (S7, S8, S9) and start_address is:

- Case 1 - Called **before** to_a - srec file contents are returned (bug)

- Case 2 - Called **after** to_a - lowest address from the data records is returned

There are 2 options to fix the bug in case 1:

- Option 1 (this PR) - Return nil - maintains current behavior with minimal change; keeps the ability to make decisions based on whether a start address record exists

- Option 2 - Return the lowest address from the data records; this would always return the same value regardless of whether to_a has been called, but there is no longer a way to tell if the jump address was provided

- Option 3 - Same as option 2, with an additional method that always returns nil or the jump address from the input

I chose option 1 because it is the smallest change.

### CODE REVIEW

**Comment by pderouen** [comment]
@ginty @coreyeng @chrisnappi any thoughts on this? I think any of the 3 options listed would be transparent to any apps that use this plugin. I'm still on the fence between the options I listed to correct the bug. I don't like that the start_address method can return something different depending on when it's called. But, I also don't like changing the existing behavior that has been in place all along.

**Comment by ginty** [comment]
I would say that the original intent here was to do what this PR actually does, return nil when no start address is found.
I think it was just bad coding on my part that returned the array by accident.

These days in new code I actively avoid returning nil (a subsequent no method error on nil is not helpful to anyone) and instead prefer an error to be raised, so I would actually vote for that in this case, though I would also go along with nil.

**Comment by pderouen** [comment]
Thanks for the feedback @ginty. After thinking on it some more, I think this update is better. There was code in the to_a method that set the start_address to the lowest address of the included data. So, if to_a was called before start_address, you'd never get the jump address from the start_address method (the plugin page says it should return the execution address).

**Comment by pderouen** [comment]
Further updates:

- don't return <code>nil</code> from <code>start_address</code> method
- ensure you always get the same value (start record or lowest address) regardless of call order of <code>to_a</code> and <code>start_address</code>. This could break backward compatibility for an app that calls <code>to_a</code> first and expects the lowest address from start_address.
- added <code>has_start_record</code> to indicate if a start record was present to retain the ability to tell

There is a potential that backward compatibility would be broken with the second bullet point above. Normally, I would keep the previous behavior by default and add a create argument to use the new behavior. But, in this case I'm not sure that there is a reason to keep the old behavior. If anything, I'd add a <code>lowest_address</code> method should it be needed.

If there are no objections, I will update the documentation and merge (once approved)

**Comment by pderouen** [comment]
Before I start the update to the docs, is there any further feedback? OK with the change that I made?

**Comment by pderouen** [comment]
@coreyeng @redxeth @ginty can you mark this PR approved if there are no objections?

**Review by coreyeng — APPROVED** [review]

**Comment by redxeth** [comment]
Could a warning be added if an app were to do this ?

**Comment by pderouen** [comment]
@redxeth, sorry I'm not tracking with you. A warning if the app does what?

**Comment by pderouen** [comment]
> 
> 
> @redxeth, sorry I'm not tracking with you. A warning if the app does what?

Warn if <code>to_a</code> is called first and there is a start record (the case of potential breakage). Yes, I think that is a good idea.

**Comment by pderouen** [comment]
@redxeth I added the warning output. I will merge later today or early next week if there is no other feedback.

**Comment by redxeth** [comment]
> @redxeth, sorry I'm not tracking with you. A warning if the app does what?

Was referring to:

> This could break backward compatibility for an app that calls to_a first and expects the lowest address from start_address.

That a check could be added or something to indicate this is no longer supported.

**Pull request merged**
